services:
    kunstmaan_utilities.shell:
        class: Kunstmaan\UtilitiesBundle\Helper\Shell\Shell

    kunstmaan_utilities.cipher:
        class: Kunstmaan\UtilitiesBundle\Helper\Cipher\UrlSafeCipher
        arguments: ['%kunstmaan_utilities.cipher.secret%']

    kunstmaan_utilities.slugifier:
        class: Kunstmaan\UtilitiesBundle\Helper\Slugifier
        public: true

    kunstmaan_utilities.twig.extension:
        class: Kunstmaan\UtilitiesBundle\Twig\UtilitiesTwigExtension
        arguments: ['@kunstmaan_utilities.slugifier']
        tags:
            - { name: twig.extension }


